import board

## Pin Configuration

MOTOR0_STEP = board.GP27
MOTOR0_DIR = board.GP26

MOTOR1_STEP = board.GP21
MOTOR1_DIR = board.GP20

MOTOR2_STEP = board.GP19
MOTOR2_DIR = board.GP18

MOTOR3_STEP = board.GP17
MOTOR3_DIR = board.GP16

## Motor Parameters
STEPS_PER_REV = 200

## Speed Configuration in seconds
ONE_REV_PER_MIN = 0.3 # 60 / 200 = 0.3

## Control Configuration
# Left
LEFT_MOTOR0_DIRECTION = 0
LEFT_MOTOR0_STEPS = 1
LEFT_MOTOR0_SPEED = 0.3

LEFT_MOTOR1_DIRECTION = 0
LEFT_MOTOR1_STEPS = 1
LEFT_MOTOR1_SPEED = 0.3

LEFT_MOTOR2_DIRECTION = 0
LEFT_MOTOR2_STEPS = 1
LEFT_MOTOR2_SPEED = 0.3

LEFT_MOTOR3_DIRECTION = 0
LEFT_MOTOR3_STEPS = 1
LEFT_MOTOR3_SPEED = 0.3

# Right
RIGHT_MOTOR0_DIRECTION = 0
RIGHT_MOTOR0_STEPS = 1
RIGHT_MOTOR0_SPEED = 0.3

RIGHT_MOTOR1_DIRECTION = 0
RIGHT_MOTOR1_STEPS = 1
RIGHT_MOTOR1_SPEED = 0.3

RIGHT_MOTOR2_DIRECTION = 0
RIGHT_MOTOR2_STEPS = 1
RIGHT_MOTOR2_SPEED = 0.3

RIGHT_MOTOR3_DIRECTION = 0
RIGHT_MOTOR3_STEPS = 1
RIGHT_MOTOR3_SPEED = 0.3

# Forward
FORWARD_MOTOR0_DIRECTION = 0
FORWARD_MOTOR0_STEPS = 1
FORWARD_MOTOR0_SPEED = 0.3

FORWARD_MOTOR1_DIRECTION = 0
FORWARD_MOTOR1_STEPS = 1
FORWARD_MOTOR1_SPEED = 0.3

FORWARD_MOTOR2_DIRECTION = 0
FORWARD_MOTOR2_STEPS = 1
FORWARD_MOTOR2_SPEED = 0.3

FORWARD_MOTOR3_DIRECTION = 0
FORWARD_MOTOR3_STEPS = 1
FORWARD_MOTOR3_SPEED = 0.3

# Backward
BACKWARD_MOTOR0_DIRECTION = 0
BACKWARD_MOTOR0_STEPS = 1
BACKWARD_MOTOR0_SPEED = 0.3

BACKWARD_MOTOR1_DIRECTION = 0
BACKWARD_MOTOR1_STEPS = 1
BACKWARD_MOTOR1_SPEED = 0.3

BACKWARD_MOTOR2_DIRECTION = 0
BACKWARD_MOTOR2_STEPS = 1
BACKWARD_MOTOR2_SPEED = 0.3

BACKWARD_MOTOR3_DIRECTION = 0
BACKWARD_MOTOR3_STEPS = 1
BACKWARD_MOTOR3_SPEED = 0.3

# Up
UP_MOTOR0_DIRECTION = 0
UP_MOTOR0_STEPS = 1
UP_MOTOR0_SPEED = 0.3

UP_MOTOR1_DIRECTION = 0
UP_MOTOR1_STEPS = 1
UP_MOTOR1_SPEED = 0.3

UP_MOTOR2_DIRECTION = 0
UP_MOTOR2_STEPS = 1
UP_MOTOR2_SPEED = 0.3

UP_MOTOR3_DIRECTION = 0
UP_MOTOR3_STEPS = 1
UP_MOTOR3_SPEED = 0.3

# Down
DOWN_MOTOR0_DIRECTION = 0
DOWN_MOTOR0_STEPS = 1
DOWN_MOTOR0_SPEED = 0.3

DOWN_MOTOR1_DIRECTION = 0
DOWN_MOTOR1_STEPS = 1
DOWN_MOTOR1_SPEED = 0.3

DOWN_MOTOR2_DIRECTION = 0
DOWN_MOTOR2_STEPS = 1
DOWN_MOTOR2_SPEED = 0.3

DOWN_MOTOR3_DIRECTION = 0
DOWN_MOTOR3_STEPS = 1
DOWN_MOTOR3_SPEED = 0.3


